Vagrant.configure("2") do |config|
  
  config.vm.define "dc" do |cfg|
    cfg.vm.box = "StefanScherer/windows_2019"
    cfg.vm.communicator = "winrm"
    cfg.vm.hostname = "dc"
    cfg.winrm.basic_auth_only = true
    cfg.vm.network :private_network, ip: "192.168.38.104", gateway: "192.168.38.1", dns: "8.8.8.8"
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    cfg.vm.provision "reload"
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/vulnad.ps1", privileged: false
    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "dc"
      vb.customize ["modifyvm", :id, "--memory", 16384]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end

  config.vm.define "endpoint" do |cfg|
    cfg.vm.box = "detectionlab/win10"
    cfg.vm.hostname = "endpoint"
    cfg.vm.network :private_network, ip: "192.168.38.105", gateway: "192.168.38.1", dns: "8.8.8.8"
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true
    cfg.vm.provision "shell", path: "scripts/provision-1.ps1", privileged: false
    cfg.vm.provision "reload"
    cfg.vm.provision "shell", path: "scripts/provision-1.ps1", privileged: false

    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "endpoint"
      vb.customize ["modifyvm", :id, "--memory", 8192]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end

  config.vm.define "attacker" do |cfg|
    cfg.vm.box = "kalilinux/rolling"
    cfg.vm.network :private_network, ip: "192.168.38.106", gateway: "192.168.38.1", dns: "8.8.8.8"
    cfg.vm.provision :shell, path: "./scripts/attacker.sh"

    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "attacker"
      vb.customize ["modifyvm", :id, "--memory", 8192]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end

end  