- name: Download Windows Management Framework 5.1
  win_get_url:
    url: http://download.microsoft.com/download/6/F/5/6F5FF66C-6775-42B0-86C4-47D41F2DA187/Win8.1AndW2K12R2-KB3191564-x64.msu
    dest: C:\tmp\Win8.1AndW2K12R2-KB3191564-x64.msu

- name: Install Windows Management Framework 5.1
  win_hotfix:
    source: C:\tmp\Win8.1AndW2K12R2-KB3191564-x64.msu
    state: present
  register: hotfix_result

- name: reboot host if required
  win_reboot:
  when: hotfix_result.reboot_required

- name: Windows | Check for xRemoteDesktopAdmin Powershell module
  win_psmodule:
    name: xRemoteDesktopAdmin
    state: present

- name: Windows | Enable Remote Desktop
  win_dsc:
    resource_name: xRemoteDesktopAdmin
    Ensure: present
    UserAuthentication: Secure

- name: Windows | Check for xNetworking Powershell module
  win_psmodule:
    name: xNetworking
    state: present

- name: Firewall | Allow RDP through Firewall
  win_dsc:
    resource_name: xFirewall
    Name: "Administrator access for RDP (TCP-In)"
    Ensure: present
    Enabled: True
    Profile: "Domain"
    Direction: "Inbound"
    Localport: "3389"
    Protocol: "TCP"
    Description: "Opens the listener port for RDP"#

- name: Change the hostname inventory_hostname
  win_hostname:
    name: "{{ inventory_hostname|upper }}"
  register: res

- name: Reboot
  win_reboot:
  when: res.reboot_required
